server:
  port: 8888
  profiles:
    active: dev #激活的配置文件
  
spring:
  application:
    name: service-config-client 


introduce: main
   
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://admin:123@localhost:10086/eureka
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
